import { KeyData } from "./types";

// Based on a 30-column grid system for better alignment
// Regular keys are 2 cols wide.
export const KEYBOARD_LAYOUT: KeyData[][] = [
  // Row 1: Numbers (Total 30: 13*2 + 4)
  [
    { code: "Backquote", en: "`", km: "«", kmShift: "»", kmAlt: "‍", width: 2 },
    { code: "Digit1", en: "1", km: "១", kmShift: "!", kmAlt: "‌", width: 2 },
    { code: "Digit2", en: "2", km: "២", kmShift: "ៗ", kmAlt: "@", width: 2 },
    { code: "Digit3", en: "3", km: "៣", kmShift: '"', kmAlt: "៑", width: 2 },
    { code: "Digit4", en: "4", km: "៤", kmShift: "៛", kmAlt: "$", width: 2 },
    { code: "Digit5", en: "5", km: "៥", kmShift: "%", kmAlt: "€", width: 2 },
    { code: "Digit6", en: "6", km: "៦", kmShift: "៍", kmAlt: "៙", width: 2 },
    { code: "Digit7", en: "7", km: "៧", kmShift: "័", kmAlt: "៚", width: 2 },
    { code: "Digit8", en: "8", km: "៨", kmShift: "៏", kmAlt: "*", width: 2 },
    { code: "Digit9", en: "9", km: "៩", kmShift: "(", kmAlt: "{", width: 2 },
    { code: "Digit0", en: "0", km: "០", kmShift: ")", kmAlt: "}", width: 2 },
    { code: "Minus", en: "-", km: "ឥ", kmShift: "៌", kmAlt: "×", width: 2 },
    { code: "Equal", en: "=", km: "ឲ", kmShift: "=", kmAlt: "៎", width: 2 },
    { code: "Backspace", en: "", km: "", kmShift: "", label: "Backspace", type: "action", width: 4 },
  ],
  // Row 2: QWERTY (Total 30: 3 + 12*2 + 3)
  [
    { code: "Tab", en: "", km: "", kmShift: "", label: "Tab", type: "action", width: 3 },
    { code: "KeyQ", en: "Q", km: "ឆ", kmShift: "ឈ", width: 2 },
    { code: "KeyW", en: "W", km: "ឹ", kmShift: "ឺ", width: 2 },
    { code: "KeyE", en: "E", km: "េ", kmShift: "ែ", kmAlt: "ឯ", width: 2 },
    { code: "KeyR", en: "R", km: "រ", kmShift: "ឬ", kmAlt: "ឫ", width: 2 },
    { code: "KeyT", en: "T", km: "ត", kmShift: "ទ", width: 2 },
    { code: "KeyY", en: "Y", km: "យ", kmShift: "ួ", width: 2 },
    { code: "KeyU", en: "U", km: "ុ", kmShift: "ូ", width: 2 },
    { code: "KeyI", en: "I", km: "ិ", kmShift: "ី", kmAlt: "ឦ", width: 2 },
    { code: "KeyO", en: "O", km: "ោ", kmShift: "ៅ", kmAlt: "ឱ", width: 2 },
    { code: "KeyP", en: "P", km: "ផ", kmShift: "ភ", kmAlt: "ឰ", width: 2 },
    { code: "BracketLeft", en: "[", km: "ៀ", kmShift: "ឿ", kmAlt: "ឩ", width: 2 },
    { code: "BracketRight", en: "]", km: "ឪ", kmShift: "ឧ", kmAlt: "ឳ", width: 2 },
    { code: "Backslash", en: "\\", km: "ឮ", kmShift: "ឭ", kmAlt: "\\", width: 3 },
  ],
  // Row 3: ASDFGH (Total 30: 4 + 11*2 + 4)
  [
    { code: "CapsLock", en: "", km: "", kmShift: "", label: "Caps Lock", type: "action", width: 4 },
    { code: "KeyA", en: "A", km: "ា", kmShift: "ាំ", width: 2 },
    { code: "KeyS", en: "S", km: "ស", kmShift: "ៃ", width: 2 },
    { code: "KeyD", en: "D", km: "ដ", kmShift: "ឌ", width: 2 },
    { code: "KeyF", en: "F", km: "ថ", kmShift: "ធ", width: 2 },
    { code: "KeyG", en: "G", km: "ង", kmShift: "អ", width: 2 },
    { code: "KeyH", en: "H", km: "ហ", kmShift: "ះ", width: 2 },
    { code: "KeyJ", en: "J", km: "្", kmShift: "ញ", width: 2 },
    { code: "KeyK", en: "K", km: "ក", kmShift: "គ", width: 2 },
    { code: "KeyL", en: "L", km: "ល", kmShift: "ឡ", width: 2 },
    { code: "Semicolon", en: ";", km: "ើ", kmShift: "ោះ", kmAlt: "៖", width: 2 },
    { code: "Quote", en: "'", km: "់", kmShift: "៉", kmAlt: "ៈ", width: 2 },
    { code: "Enter", en: "", km: "", kmShift: "", label: "Enter", type: "action", width: 4 },
  ],
  // Row 4: ZXCVBN (Total 30: 5 + 10*2 + 5)
  [
    { code: "ShiftLeft", en: "", km: "", kmShift: "", label: "Shift", type: "modifier", width: 5 },
    { code: "KeyZ", en: "Z", km: "ឋ", kmShift: "ឍ", width: 2 },
    { code: "KeyX", en: "X", km: "ខ", kmShift: "ឃ", width: 2 },
    { code: "KeyC", en: "C", km: "ច", kmShift: "ជ", width: 2 },
    { code: "KeyV", en: "V", km: "វ", kmShift: "េះ", width: 2 },
    { code: "KeyB", en: "B", km: "ប", kmShift: "ព", width: 2 },
    { code: "KeyN", en: "N", km: "ន", kmShift: "ណ", width: 2 },
    { code: "KeyM", en: "M", km: "ម", kmShift: "ំ", width: 2 },
    { code: "Comma", en: ",", km: "ុំ", kmShift: "ុះ", kmAlt: ",", width: 2 },
    { code: "Period", en: ".", km: "។", kmShift: "៕", kmAlt: ".", width: 2 },
    { code: "Slash", en: "/", km: "៊", kmShift: "?", kmAlt: "/", width: 2 },
    { code: "ShiftRight", en: "", km: "", kmShift: "", label: "Shift", type: "modifier", width: 5 },
  ],
  // Row 5: Bottom (Total 30)
  [
    { code: "ControlLeft", en: "", km: "", kmShift: "", label: "Ctrl", type: "modifier", width: 3 },
    { code: "Fn", en: "", km: "", kmShift: "", label: "Fn", type: "modifier", width: 2 },
    { code: "MetaLeft", en: "", km: "", kmShift: "", label: "Win", type: "modifier", width: 3 },
    { code: "AltLeft", en: "", km: "", kmShift: "", label: "Alt", type: "modifier", width: 3 },
    { code: "Space", en: "", km: "", kmShift: "", label: "Space", type: "char", width: 9 },
    { code: "AltRight", en: "", km: "", kmShift: "", label: "Alt", type: "modifier", width: 3 },
    { code: "ControlRight", en: "", km: "", kmShift: "", label: "Ctrl", type: "modifier", width: 3 },
    { code: "ArrowLeft", en: "", km: "", kmShift: "", label: "", type: "action", icon: "ChevronLeft", width: 1 },
    { code: "ArrowDown", en: "", km: "", kmShift: "", label: "", type: "action", icon: "ChevronDown", width: 1 },
    { code: "ArrowUp", en: "", km: "", kmShift: "", label: "", type: "action", icon: "ChevronUp", width: 1 },
    { code: "ArrowRight", en: "", km: "", kmShift: "", label: "", type: "action", icon: "ChevronRight", width: 1 },
  ],
];
